# generated by cabal-rpm-2.3.0 --standalone
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%undefine with_ghc_prof
%undefine with_haddock
%global without_prof 1
%global without_haddock 1
%global debug_package %{nil}

Name:           ghc-tags
Version:        1.8
Release:        1%{?dist}
Summary:        Utility for generating ctags and etags with GHC API

License:        MPL-2.0
URL:            https://hackage.haskell.org/package/ghc-tags
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz
Source1:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}.cabal#/%{name}-%{version}.cabal
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  dos2unix
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-aeson-devel
BuildRequires:  ghc-async-devel
BuildRequires:  ghc-attoparsec-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-filepath-devel
%if %{defined ghc_major}
BuildRequires:  ghc-ghc-devel
BuildRequires:  ghc-ghc-boot-devel
%else
#BuildRequires:  ghc-ghc-lib-devel
%endif
BuildRequires:  ghc-ghc-paths-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-stm-devel
BuildRequires:  ghc-temporary-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-vector-devel
BuildRequires:  ghc-yaml-devel
BuildRequires:  help2man
BuildRequires:  cabal-install
# for missing dep 'ghc-lib':
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-exceptions-devel
BuildRequires:  ghc-ghc-lib-parser-devel
BuildRequires:  ghc-hpc-devel
BuildRequires:  ghc-parsec-devel
BuildRequires:  ghc-pretty-devel
BuildRequires:  ghc-transformers-devel
BuildRequires:  ghc-unix-devel
# for missing dep 'semaphore-compat':
BuildRequires:  ghc-exceptions-devel
BuildRequires:  ghc-unix-devel
# End cabal-rpm deps

%description
Utility for generating etags (Emacs) and ctags (Vim and other editors) with GHC
API for efficient project navigation.


%prep
# Begin cabal-rpm setup:
%setup -q
dos2unix -k -n %{SOURCE1} %{name}.cabal
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%global cabal_install %{_bindir}/cabal
%cabal_install update
%if %{defined rhel} && 0%{?rhel} < 9
%cabal_install sandbox init
%cabal_install install
%endif
# End cabal-rpm build


%install
# Begin cabal-rpm install
mkdir -p %{buildroot}%{_bindir}
%if %{defined fedora} || 0%{?rhel} >= 9
%ghc_set_gcc_flags
%cabal_install install --install-method=copy --enable-executable-stripping --installdir=%{buildroot}%{_bindir}
%else
for i in .cabal-sandbox/bin/*; do
strip -s -o %{buildroot}%{_bindir}/$(basename $i) $i
done
%endif

set noclobber
mkdir -p %{buildroot}%{bash_completions_dir}
%{buildroot}%{_bindir}/%{name} --bash-completion-script %{name} | sed s/filenames/default/ > %{buildroot}%{bash_completions_dir}/%{name}

mkdir -p %{buildroot}%{_mandir}/man1/
help2man --no-info %{buildroot}%{_bindir}/%{name} > %{buildroot}%{_mandir}/man1/%{name}.1
# End cabal-rpm install


%files
# Begin cabal-rpm files:
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/%{name}
%{bash_completions_dir}/%{name}
%{_mandir}/man1/%{name}.1*
# End cabal-rpm files


%changelog
* Wed Mar 12 2025 Jens Petersen <petersen@redhat.com> - 1.8-1
- https://hackage.haskell.org/package/ghc-tags-1.8/changelog

* Wed Oct 30 2024 Jens Petersen <petersen@redhat.com> - 1.7-1
- update to 1.7 (for ghc-9.6)

* Mon May 16 2022 Jens Petersen <petersen@redhat.com> - 1.5-1
- spec file generated by cabal-rpm-2.0.12
