# generated by cabal-rpm-2.0.12 --standalone
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global ghc_name ghc9.2

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%undefine with_ghc_prof
%undefine with_haddock
%global without_prof 1
%global without_haddock 1
%global debug_package %{nil}

Name:           ghc-tags
Version:        1.5
Release:        1%{?dist}
Summary:        Utility for generating ctags and etags with GHC API

License:        MPLv2.0
Url:            https://hackage.haskell.org/package/%{name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
%if %{defined ghc_name}
BuildRequires:  ghc9.2
%else
BuildRequires:  ghc-aeson-devel
BuildRequires:  ghc-async-devel
BuildRequires:  ghc-attoparsec-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-filepath-devel
#BuildRequires:  ghc-ghc-lib-devel
BuildRequires:  ghc-ghc-paths-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-stm-devel
BuildRequires:  ghc-temporary-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-vector-devel
BuildRequires:  ghc-yaml-devel
%endif
BuildRequires:  cabal-install > 1.18
%if %{undefined ghc_name}
# for missing dep 'ghc-lib':
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-ghc-lib-parser-devel
BuildRequires:  ghc-hpc-devel
BuildRequires:  ghc-pretty-devel
BuildRequires:  ghc-rts-devel
BuildRequires:  ghc-transformers-devel
BuildRequires:  ghc-unix-devel
%endif
# End cabal-rpm deps

%description
Utility for generating etags (Emacs) and ctags (Vim and other editors) with GHC
API for efficient project navigation.


%prep
# Begin cabal-rpm setup:
%setup -q
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
cabal update
%if 0%{?rhel} && 0%{?rhel} < 9
cabal sandbox init
cabal install
%endif
# End cabal-rpm build


%install
# Begin cabal-rpm install
mkdir -p %{buildroot}%{_bindir}
%if 0%{?fedora} >= 33 || 0%{?rhel} > 8
%if 0%{?fedora} >= 36
%ghc_set_gcc_flags
%endif
cabal install -w ghc-9.2.2 --install-method=copy --enable-executable-stripping --installdir=%{buildroot}%{_bindir}
%else
for i in .cabal-sandbox/bin/*; do
strip -s -o %{buildroot}%{_bindir}/$(basename $i) $i
done
%endif
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions/
%{buildroot}%{_bindir}/%{name} --bash-completion-script %{name} | sed s/filenames/default/ > %{buildroot}%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm install


%files
# Begin cabal-rpm files:
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/%{name}
%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm files


%changelog
* Mon May 16 2022 Jens Petersen <petersen@redhat.com> - 1.5-1
- spec file generated by cabal-rpm-2.0.12
